### ISSUE TITLE
I'd love to better understand what this is.

### ISSUE THREAD

**Issue by gltovar** [back2dos/lessie#3]
Hi, I was toying around with html haxe, and saw this project and decided to explore it a bit more. To be honest I don't know exactly what your project does, but I am using LESS for my css generator so I would probably be worth knowing. If you had a sample project or a bit of detailed walk though on how to get started it might help out more people wandering by.

**Comment by back2dos** [comment]
Well, you can see it in use here: https://github.com/MVCoconut/examples-todomvc/tree/master/src/todomvc/ui

You can associate any class with less files. The classes that are compiled and not DCEd are passed to `lessc`.

As for getting started, you install the library and add `-lib lessie` to your build, nothing more ^^

**Comment by back2dos** [comment]
Not sure what else to add ... but if anything is left unclear, please ask away ;)
